Added get_frame with tests.
Orchard-Ultrasound-Innovation/SimpleByteStuffing.jl pull request #1
Opened 2022-07-13 00:31 UTC by longsnn

get_frame 
parameters: command byte, read/write byte, and payload array
returns: byte stuffed frame

2022-07-13 23:06 UTC, longsnn commented
> You can use a `UInt8` buffer instead of an `Any` buffer.
> 
> ```julia
> julia> typeof([])
> Vector{Any} (alias for Array{Any, 1})
> 
> julia> typeof(Any[])
> Vector{Any} (alias for Array{Any, 1})
> 
> julia> typeof(UInt8[])
> Vector{UInt8} (alias for Array{UInt8, 1})
> ```

Fixed, thanks.

2022-07-19 18:09 UTC, mofii commented on src/bytestuffing.jl
> +    packet = []
Here's another Any buffer

2022-07-19 18:09 UTC, mofii commented on src/bytestuffing.jl
> +    bs_data = []
Any buffer

2022-07-19 18:10 UTC, mofii commented on src/bytestuffing.jl
> +    data = []
Any buffer

2022-07-19 18:11 UTC, mofii commented on src/bytestuffing.jl
> +end
Add a return statement

2022-07-19 18:12 UTC, mofii commented on src/bytestuffing.jl
> +    packet = []
Changing to UInt8 buffer also removes the convert() command on line 16.

2022-07-19 18:13 UTC, mofii commented on src/bytestuffing.jl
> +    return UInt8(checksum)
Do you need to parse to UInt8 twice in this function?

2022-07-19 18:13 UTC, mofii commented on src/bytestuffing.jl
> +end
end with a newline

2022-07-19 18:14 UTC, mofii commented on src/bytestuffing.jl
> +
`destuff_packet()` is the first function call in `parse_packet()` and should be placed here.

2022-07-19 18:15 UTC, mofii commented on src/bytestuffing.jl
> +            push!(data, xor( bs_data[i] ,0x20))
", " instead of " ,"

2022-07-19 18:16 UTC, mofii commented on src/bytestuffing.jl
> +            i = i+1
Add space around the operator, just like in line 85

2022-07-20 00:39 UTC, longsnn commented on src/SimpleByteStuffing.jl
> +read_or_write: acceptables values are READ and WRITE
I'll make the changes, thanks.

2022-07-20 00:40 UTC, longsnn commented on src/bytestuffing.jl
> +    return UInt8(checksum)
No, the last one isn't necessary.

2022-07-22 01:27 UTC, mofii requested changes
Yup, getting close!

2022-07-22 01:27 UTC, mofii commented on src/SimpleByteStuffing.jl
> +export READ, WRITE
This is no longer necessary

2022-07-22 01:27 UTC, mofii commented on src/bytestuffing.jl
> +const READ = "READ"
These definitions are no longer necessary, you can just use the string directly

2022-07-22 01:27 UTC, mofii commented on src/bytestuffing.jl
> +    for i in data
```julia
for byte in data
```

2022-07-22 01:27 UTC, mofii commented on src/bytestuffing.jl
> +const FLAG = [SOP, EOP, ESC]
FLAG -> FLAGS

2022-07-22 01:27 UTC, mofii commented on src/bytestuffing.jl
> +    push!(frame, command | (rw<<7) )
Why do you need to bit shift here?
Wouldn't it be easier to define `rw` with the correct value on line 37?

2022-07-22 01:27 UTC, mofii commented on src/bytestuffing.jl
> +
remove space

2022-07-22 01:27 UTC, mofii commented on src/bytestuffing.jl
> +    checksum = get_checksum(frame)
`compute_checksum()`

2022-07-22 01:27 UTC, mofii commented on src/bytestuffing.jl
> +    crc = get_checksum(data)
It's not a CRC but a checksum

2022-07-22 01:27 UTC, mofii commented on src/bytestuffing.jl
> +
remove empty line

2022-07-22 01:27 UTC, mofii commented on src/bytestuffing.jl
> +    i = 1
`i` -> `byte_idx`

2022-07-22 01:27 UTC, mofii commented on test/runtests.jl
> +
Another test: where you generate a long (1000-ish) random UInt8 vector as payload, pack it, parse it, compare the parsed data with the original payload

2022-07-22 21:38 UTC, longsnn commented on src/bytestuffing.jl
> +    push!(frame, command | (rw<<7) )
Yes, that would be easier. I changed it to combine(command, read_or_write).

2022-07-22 21:42 UTC, longsnn commented on src/bytestuffing.jl
> +    checksum = get_checksum(frame)
Would `checksum(data)` work as well?

2022-07-22 21:43 UTC, longsnn commented on test/runtests.jl
> +
Good idea, thanks.

2022-08-03 01:11 UTC, stevenaleung requested changes
Looks ready for a merge after this last change

2022-08-03 01:11 UTC, stevenaleung commented on src/bytestuffing.jl
> +function checksum(data::Vector{UInt8})
Since checksum is a noun, renaming this function to `compute_checksum()` makes its intent clearer and would make it pair well with `verify_checksum()`

2022-08-03 18:02 UTC, longsnn commented on src/bytestuffing.jl
> +function checksum(data::Vector{UInt8})
Makes sense. Thanks.

2022-08-03 19:08 UTC, stevenaleung approved these changes
Ready for merge 👍🏼

2022-08-03 19:16 UTC, merged